### ISSUE TITLE
Agv's voor de boot komen uit de lucht naar punt Q ( van storage -> boot )

### ISSUE THREAD

**Issue by MorenoB** [pasibun/containing#126]
dit gebeurt als we met de officiele xml's werken

**Comment by thomw201** [comment]
Dit kwam doordat er geen getWorldTranslation gebruikt mag worden nadat de agvs zo geinitialiseerd zijn, de waardes die van getWorldTranslation komen zijn dan altijd 0 ofzo.. iig is gefixed in pull req door waardes handmatig mee te geven en aan de hand van een boolean deze op de eerste beweging te gebruiken

**Comment by jeroen940** [comment]
:+1:

**Comment by MorenoB** [comment]
fixed :+1:
